export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const EMPTY_PRODUCTS_BY_CATEGORY = "EMPTY_PRODUCTS_BY_CATEGORY";
export const GET_ONE_PRODUCTS = "GET_ONE_PRODUCTS";
export const EMPTY_ONE_PRODUCTS = "EMPTY_ONE_PRODUCTS";